### ISSUE TITLE
前端项目访问不到go-chatgpt-api

### ISSUE THREAD

**Issue by goyeee** [dqzboy/ChatGPT-Proxy#12]
![image](https://user-images.githubusercontent.com/45221885/236681388-0eff637f-bf88-410a-aefa-e63de394dc64.png)

我的前端项目已配置好，但是无法使用，提示如上图。

部署环境：云服务器；目前已将go-chatgpt-api 和 chatgpt-web 都通过docker-compose 起来了，并且解决了容器网络ping不通的问题。chatgpt-web容器已可以wget openai.com
调试：1.通过前端项目发送消息时，go-chatgpt-api容器 docker logs -f go-chatgpt-api  没有出现请求日志
                  2.进入chatgpt-web容器，wget http://go-chatgpt-api:8080/chatgpt/conversation  ,返回 HTTP/1.1 403 Forbidden （说明可以访问通，但必须用POST方式，因为chatgpt-web容器没有curl，就没尝试POST）
                   3.通过宿主机， curl 127.0.0.1:8080/chatgpt/conversation ，返回 {"errorMessage":"Missing accessToken."}。

以下是我的yml文件和nginx 配置，请问哪里出了问题？

![image](https://user-images.githubusercontent.com/45221885/236682120-c242c418-08ca-480e-adfd-d81dcd768759.png)

![image](https://user-images.githubusercontent.com/45221885/236682171-1a5f2a8f-3368-483b-a704-9b70b5fa3f3b.png)

![image](https://user-images.githubusercontent.com/45221885/236682248-bdb1801d-6b91-4c4a-929e-bad6c41e6c35.png)

**Comment by dqzboy** [comment]
https://github.com/linweiyuan/go-chatgpt-api
![image](https://user-images.githubusercontent.com/42825450/236682688-6ab3bc95-8fad-44d3-9386-d6e4b8ea2a47.png)
API 这个

**Comment by goyeee** [comment]
对的，是这个api.

chatgpt-web为：[Chanzhaoyu](https://github.com/Chanzhaoyu)
/[chatgpt-web](https://github.com/Chanzhaoyu/chatgpt-web)

**Comment by dqzboy** [comment]
看下接口，改成我上面截图那个

**Comment by goyeee** [comment]
如何查看？ 是下面这个吗？
1.
![image](https://user-images.githubusercontent.com/45221885/236683156-aea4a156-d8b0-4724-8e81-c6e8ad6cdc8b.png)

2.
![image](https://user-images.githubusercontent.com/45221885/236683390-5b3afc9d-44cd-489c-8f21-322a5b49e3ae.png)

**Comment by goyeee** [comment]
要看chatgpt-web的源码请求的地址是什么吗？ 我要怎么看呢？

**Comment by dqzboy** [comment]
你用的API呀 不需要配置反向代理

**Comment by goyeee** [comment]
![image](https://user-images.githubusercontent.com/45221885/236685017-5ff873ba-4647-458a-996f-1792cb7bc9f0.png)

我将API_REVERSE_PROXY 去除后， go-chatgpt-api容器 docker logs -f go-chatgpt-api    还是没有出现请求日志

**Comment by dqzboy** [comment]
你要使用accesstoken，然后配置API_REVERSE_PROXY

**Comment by goyeee** [comment]
![image](https://user-images.githubusercontent.com/45221885/236685138-a3f54d6f-8c13-4c20-8e11-f9026dc15c8b.png)

我将API_REVERSE_PROXY 置为空了，go-chatgpt-api容器 docker logs -f go-chatgpt-api  还是没有出现请求日志

**Comment by dqzboy** [comment]
![image](https://user-images.githubusercontent.com/42825450/236685493-faec9fec-fd8e-4a39-9fa8-5b4c52a7c9bf.png)

**Comment by goyeee** [comment]
感谢，已经有日志了。
但是返回了 ：[OpenAI] 服务器拒绝访问，请稍后再试 | Server refused to access, please try again later

如下图，
![image](https://user-images.githubusercontent.com/45221885/236686945-7e37fc84-f39b-4d6e-a5aa-64292db7edb9.png)



这是我修改后的yml，只取了 一个 accessToken，是这个长度吧，还是说整体粘贴进去？
![image](https://user-images.githubusercontent.com/45221885/236686731-0e7b1db6-0b2a-4b53-8fc7-346096dde114.png)

**Comment by dqzboy** [comment]
新建一个会话

**Comment by goyeee** [comment]
还不行呢
![image](https://user-images.githubusercontent.com/45221885/236687274-d3c63081-0658-4f12-904e-c2ea3dd4a8ca.png)

**Comment by dqzboy** [comment]
你服务器是哪的？能访问openai吗？

**Comment by goyeee** [comment]
阿里云，已经参考文章 “[国内服务器实现科学上网](https://www.dqzboy.com/13754.html)” 能否在go-chatgpt-api容器内访问到openai 了。 wget platform.openai.com 返回 了index.html

如下。
![image](https://user-images.githubusercontent.com/45221885/236687450-868d014d-6d16-4862-9eef-8094554760c1.png)

**Comment by dqzboy** [comment]
应该还是跟你代理地址有关  换个节点再试

**Comment by dqzboy** [comment]
是不是go-chatgpt-api返回的403

**Comment by goyeee** [comment]
貌似是的。
请看下图日志
![image](https://user-images.githubusercontent.com/45221885/236687786-e27fa80e-3b76-466c-af30-b4bb5269f090.png)

**Comment by dqzboy** [comment]
那你使用基于Cloudflare WARP模式 重新部署下

**Comment by goyeee** [comment]
意思是应该不是节点的问题对吧？ 我切换了节点也不行。

下图

![image](https://user-images.githubusercontent.com/45221885/236688057-42b1d6bd-e8af-4df8-95f6-9b09cd2a9edd.png)

**Comment by dqzboy** [comment]
节点问题，你节点选择手动选择，然后手动选择 选择美国节点试试；然后看下面板日志里面 openai走的哪个节点

**Comment by goyeee** [comment]
这里：
![image](https://user-images.githubusercontent.com/45221885/236688513-ecd27fdf-fbc1-47b4-a94c-9b7dae335a15.png)

然后我进入go-chatgpt-api容器，也得到了403 

![image](https://user-images.githubusercontent.com/45221885/236688556-e25b0574-c5ec-4b5f-b8d6-e7fa00a35d1b.png)

**Comment by dqzboy** [comment]
换成自动切换  让clash自动选择节点  实在不行 就换成WARP那个镜像

**Comment by goyeee** [comment]
好的 谢谢 我再试试

**Comment by DuanShaoCheng** [comment]
问题有解决吗 我这表现是 gpt3 模型访问没问题 gpt4 会出现 [OpenAI] 服务器拒绝访问，请稍后再试 | Server refused to access, please try again later

**Comment by dqzboy** [comment]
更新下docker-compose.yml，然后拉取最新的镜像

**Comment by DuanShaoCheng** [comment]
> 更新下docker-compose.yml，然后拉取最新的镜像

根据新的镜像和compose一切正常了，感谢～～

**Comment by DuanShaoCheng** [comment]
稳定了一段时间，问题再次出现，表现还是3.5正常, 4出现问题~

**Comment by dqzboy** [comment]
token还是API

**Comment by DuanShaoCheng** [comment]
> token还是API

token

**Comment by dqzboy** [comment]
昨天更新了docker-compose.yml  你现在是使用的最新的docker-compose.yml吗？

**Comment by DuanShaoCheng** [comment]
> 昨天更新了docker-compose.yml 你现在是使用的最新的docker-compose.yml吗？

我昨天更新了最新的镜像和最新的 docker-compose.yml 功能正常了，今早出现了问题，我刚刚查看发现镜像又有更新，我再次更新，现在恢复正常了~~ 感谢~
