### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by goyeee** [dqzboy/ChatGPT-Proxy#13]
你好，目前我使用一台vps1(无魔法），根据chenzhaoyu94/chatgpt-web 使用dokcer-compose 搭建了gpt前端，我想转发到有魔法的另一台vps2上，所以在另一台搭建了 inweiyuan/go-chatgpt-api 提供接口。但是使用时，vps1的日志提示404。

1.目前vps2是可以通过 vps2 IP:8080/chatgpt/conversation 访问的，提示{"errorMessage":"Missing accessToken."}，说明调用通常。
2.vps1日志提示的url地址是：http://vps2 IP:8080/chatgpt/conversation/v1/chat/completion，多出了 v1/chat/completion的路径。

以下是日志，请帮忙分析一下是什么原因？

vps1：chenzhaoyu94/chatgpt-web日志：
![image](https://github.com/dqzboy/ChatGPT-Proxy/assets/45221885/39310fb6-e11d-4aab-99de-9c9989f695e5)

vps2: go-chatgpt-api日志：
![image](https://github.com/dqzboy/ChatGPT-Proxy/assets/45221885/8bb7a375-87d8-4316-b4a1-8547e362361b)

**Comment by dqzboy** [comment]
v1/chat/completion  是前端传过去的吧

**Comment by dqzboy** [comment]
apikey：
```shell
OPENAI_API_BASE_URL=xxx
```

accesstoken:
```shell
API_REVERSE_PROXY=xxx
```

具体如何配置查看[README](https://github.com/dqzboy/ChatGPT-Proxy/blob/main/README.md)
