### ISSUE TITLE
如何搭建和fakeopen.com结构相同的API

### ISSUE THREAD

**Issue by Nothingness-Void** [dqzboy/ChatGPT-Proxy#14]
### ⚠️ 搜索是否存在类似issue

- [X] 我已经搜索过issues和disscussions，没有发现相似issue

### 总结

https://[fakeopen.nothingnessvoid.tech/api/](https://fakeopen.nothingnessvoid.tech/api/) 
如题 我看别人搭建的进去之后访问都会提示
![image](https://github.com/dqzboy/ChatGPT-Proxy/assets/55913486/6b7a5117-e847-45f7-b363-40d5b32b9514)
但是我按照教程的脚本搭建完之后是
![image](https://github.com/dqzboy/ChatGPT-Proxy/assets/55913486/5dc8ef00-39d9-4e6d-9c7c-9b9206002997)

**Comment by dqzboy** [comment]
你需要改 pandora 代码里面的请求接口地址 为此项目的接口才可以；具体怎么修改可以到pandora问一下

**Comment by Nothingness-Void** [comment]
> 你需要改 pandora 代码里面的请求接口地址 为此项目的接口才可以；具体怎么修改可以到pandora问一下

https://[ai.fakeopen.com](https://ai.fakeopen.com/)/pandora调用的就是这个 我想问咱们这个项目能建成这样子吗

**Comment by dqzboy** [comment]
这个项目里问一下  [linweiyuan/go-chatgpt-api](https://github.com/linweiyuan/go-chatgpt-api)

**Comment by Nothingness-Void** [comment]
> 这个项目里问一下 [linweiyuan/go-chatgpt-api](https://github.com/linweiyuan/go-chatgpt-api)

好的 感谢大佬

**Comment by Nothingness-Void** [comment]
对了大佬，我想问一下一键脚本搭建的服务怎么修改端口 或者怎么改成纯域名访问 我目前访问都需要域名:8080 才能够访问

**Comment by dqzboy** [comment]
修改docker-compose.yml里面的ports 第一个 8080为80，然后重启容器

**Comment by Nothingness-Void** [comment]
> 修改docker-compose.yml里面的ports 第一个 8080为80，然后重启容器

成功了 感谢大佬
