### ISSUE TITLE
Failed to get arkose token, GPT4 token还是用不了

### ISSUE THREAD

**Issue by dapeng1115** [dqzboy/ChatGPT-Proxy#16]
### 前置确认

- [X] 我确认我的网络可以访问openai，使用的是最新脚本，并且服务器规格 > 1C1G

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Ubuntu

### 复现步骤 🕹

按照无warp部署docker image

### 问题描述 😯

arkose token还是会报错
无论设置还是不设置ARKOSE_TOKEN_URL

### 终端日志 📒

[GIN] 2023/08/22 - 13:06:27 | 307 |    1.749772ms |   *.*.*.* | POST     "/api/conversation/"
INFO[0023] gpt-4                             
WARN[0023] Failed to get arkose token.       
[GIN] 2023/08/22 - 13:06:28 | 403 |  492.869344ms |     *.*.*.* | POST     "/chatgpt/backend-api/conversation"

**Comment by dqzboy** [comment]
公共的不行的话，就得自行部署了
