### ISSUE TITLE
使用一键脚本，停在Installing postfix...不动

### ISSUE THREAD

**Issue by li258w** [dqzboy/ChatGPT-Proxy#19]
### 前置确认

- [X] 我确认我的网络可以访问openai，使用的是最新脚本，并且服务器规格 > 1C1G

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Ubuntu

### 复现步骤 🕹

Device "enp0s6
enp0s6" does not exist.
This script may not be fully compatible with the current architecture: aarch64
------------------------------------< 提示 >-------------------------------------
                        检测服务器是否能够访问chat.openai.com                   
------------------------------------< END >-------------------------------------
Testing connection to chat.openai.com...
Connection successful!
╭──────────────────────────────────────────────────────╮
│                                                      │
│  提示：此处测试结果仅代表你的服务器可以访问OPENAI    │
│       是否可以使用OPENAI接口还需要部署完成之后测试!  │
│                                                      │
╰──────────────────────────────────────────────────────╯
--------------------------------------------------------
System release:: Ubuntu
System version: 20.04.6 LTS (Focal Fossa)
System ID: ubuntu
System ID Like: debian
--------------------------------------------------------
------------------------------------< Firewall && SELinux detection. >-------------------------------------
Firewall has been disabled.
------------------------------------< Install necessary system components >-------------------------------------
lsof Already installed, skip...
jq Already installed, skip...
wget Already installed, skip...
Installing postfix ...

### 问题描述 😯

运行一键脚本后，停在Installing postfix ...这步，等一小时也没有反应，多次尝试总是同样的问题。

### 终端日志 📒

```log
<此处粘贴终端日志>
```

**Comment by dqzboy** [comment]
已更新，获取最新的脚本，可以跳过对应的软件包安装
